
server:
  port: 9900


swaggerdoc:
         url: https://github.com/SpringForAll/spring-boot-starter-swagger
swagger:
   enabled: true

### thymeleaf\u914D\u7F6E\u4FE1\u606F
# \u4E0D\u542F\u7528\u7F13\u5B58
spring:
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      servlet:
        content-type: text/html
